### ISSUE TITLE
请问作者还计划加入其它表达组件么？

### ISSUE THREAD

**Issue by qpskcn1** [kennylbj/patrick-wechat#3]
除了Radio,请问作者有没有计划加入Input和TextArea之类的表单组件？

**Comment by kennylbj** [comment]
More components including multiple options selector, textfield will be introduced in the future. Or you can check [taro-ui](https://github.com/NervJS/taro-ui) for more components for now.

**Comment by qpskcn1** [comment]
Thank you for replying! I'm actually working on it.
