### ISSUE TITLE
小白问

### ISSUE THREAD

**Issue by mark-jy** [kennylbj/patrick-wechat#5]
用微信小程序编译报错：
“未找到入口 app.json 文件，或者文件读取失败，请检查后重新编译。”

能看到app.json文件在scr下，但是还是报错

**Comment by mark-jy** [comment]
不知道这里是否有问题

`patrick-wechat-master % yarn run dev:weapp
yarn run v1.22.4
$ npm run build:weapp -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/l7/pddq3wcd6t51g_5fsz6z1k0w0000gp/T/yarn--1592996958384-0.14696055855546453/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> patrick-wechat@1.1.0 build:weapp /Users/mark/Downloads/patrick-wechat-master
> taro build --type weapp "--watch"

👽 Taro v2.2.9


当前项目使用了 sass，请安装插件 @tarojs/plugin-sass，并且在 plugins 中进行配置，否则将无法编译 sass 文件！
参考文档：https://nervjs.github.io/taro/docs/config-detail#plugins

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! patrick-wechat@1.1.0 build:weapp: `taro build --type weapp "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the patrick-wechat@1.1.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2020-06-24T11_09_26_945Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`

**Comment by mark-jy** [comment]
patrick-wechat-master % yarn run dev:weapp
yarn run v1.22.4
$ npm run build:weapp -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/l7/pddq3wcd6t51g_5fsz6z1k0w0000gp/T/yarn--1592996958384-0.14696055855546453/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> patrick-wechat@1.1.0 build:weapp /Users/mark/Downloads/patrick-wechat-master
> taro build --type weapp "--watch"

👽 Taro v2.2.9


当前项目使用了 sass，请安装插件 @tarojs/plugin-sass，并且在 plugins 中进行配置，否则将无法编译 sass 文件！
参考文档：https://nervjs.github.io/taro/docs/config-detail#plugins

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! patrick-wechat@1.1.0 build:weapp: `taro build --type weapp "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the patrick-wechat@1.1.0 build:weapp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mark/.npm/_logs/2020-06-24T11_09_26_945Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


不知道这里运行yarn run dev:weapp是否有问题，多谢！

**Comment by kennylbj** [comment]
Try to run:

```bash
yarn run dev:weapp
```

and then import project to WeChat Developer Tool.

**Comment by mark-jy** [comment]
更新taro后编译成功，多谢！
