### ISSUE TITLE
装不上sass啊

### ISSUE THREAD

**Issue by wulivictor** [kennylbj/patrick-wechat#6]

**Comment by kennylbj** [comment]
Fixed in commit https://github.com/kennylbj/patrick-wechat/commit/47468399924bba39e92191867de142ee88722e67

Please pull the lastest source code and then re-import to WeChat developer tool.

**Comment by kennylbj** [comment]
Note: The latest version of taro-cli(2.2.9 for now) is recommended for compiling and building this project.

**Comment by wulivictor** [comment]
ok， I will try again.  thanks you

**Comment by wulivictor** [comment]
![image](https://user-images.githubusercontent.com/32082243/85729154-24607780-b72b-11ea-885c-c3db204233e5.png)
![image](https://user-images.githubusercontent.com/32082243/85729185-2a565880-b72b-11ea-974d-38d8b2c56ff3.png)
还是报错 啊

**Comment by wulivictor** [comment]
![image](https://user-images.githubusercontent.com/32082243/85729320-4bb74480-b72b-11ea-8ca8-042b9a371b9c.png)
还是报错啊

**Comment by kennylbj** [comment]
rm -rf node_modules

yarn install
