### ISSUE TITLE
请问是否有办法将该项目中f2-canvase画出的图设置为随View组件移动？

### ISSUE THREAD

**Issue by c747903646** [kennylbj/patrick-wechat#8]
项目中result部分基于f2画出的图像似乎只能按屏幕百分比设定位置，而不能被随着View组件的排列移动位置？比如我改成如下的代码，希望画出来的图表能出现在text1和text2之间，但是并不能成功，text1和text2会被布局到相邻的位置，但图表却会出现在页面正中间。求教需要如何设置才能实现目标布局？

`
<View>text1</View>
<View style='width:100%;height:100px'><chart-canvas className='chart' opts={opts} /></View>
<View>text2</View>
`

**Comment by kennylbj** [comment]
参考Flex布局

**Comment by c747903646** [comment]
成功了，原来是得在/components/chart-canvas/index.wxml里设置style才能生效啊，我之前一直是在page里的index设置style来着orz
